import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Schema as MongooseSchema, Types } from 'mongoose';

// Utility function to handle empty string values
const sanitizeNumber = (val: any) => (val === '' ? null : val);

// Subdocument schema for Quantity Threshold Adjustments
@Schema({ _id: false })
class QuantityThresholdAdjustment {
  @Prop({ type: Number })
  thresholdValue: number;

  @Prop({ type: String })
  comparisonOperator: string;

  @Prop({ type: Number })
  adjustedValue: number;
}

// Subdocument schema for Allowed Quantities by Price Range
@Schema({ _id: false })
class AllowedQuantitiesByPriceRange {
  @Prop({ type: Number })
  minPrice: number;

  @Prop({ type: Number })
  maxPrice: number;

  @Prop({ type: Number })
  allowedQuantity: number;
}

// Subdocument schema for Store Allowed Quantities
@Schema({ _id: false })
class StoreAllowedQuantities {
  @Prop({ type: Number })
  quantityOffset: number;

  @Prop({ type: Number })
  maxQuantityLimitEnabled: number;

  @Prop({ type: Number })
  maxAllowedQuantity: number;

  @Prop({ type: [QuantityThresholdAdjustment], default: [] })
  quantityThresholdAdjustments: QuantityThresholdAdjustment[];

  @Prop({ type: [AllowedQuantitiesByPriceRange], default: [] })
  quantitiesByPriceRange: AllowedQuantitiesByPriceRange[];
}

// Subdocument schema for API OAuth Token
@Schema({ _id: false })
class ApiOAuthToken {
  @Prop({ type: MongooseSchema.Types.Mixed })
  accessToken: any;

  @Prop({ type: Date })
  accessTokenUpdatedDate: Date;

  @Prop({ type: MongooseSchema.Types.Mixed })
  applicationAccessToken: any;

  @Prop({ type: Date })
  applicationAccessTokenUpdatedDate: Date;

  @Prop({ type: MongooseSchema.Types.Mixed })
  refreshToken: any;

  @Prop({ type: Boolean })
  refreshTokenValid: boolean;

  @Prop({ type: Date })
  refreshTokenUpdatedDate: Date;

  @Prop({ type: String, enum: ['autoGenerated', 'manual'] })
  source: string;
}

// Subdocument schema for Supplier Sourcing Priority
@Schema({ _id: false })
class SupplierSourcingPriority {
  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'SupplierConfig' })
  supplierId: Types.ObjectId;

  @Prop({ type: Number })
  priority: number;
}

// Subdocument schema for Price Offset Tolerance
@Schema({ _id: false })
class PriceOffsetTolerance {
  @Prop({ type: Number })
  value: number;

  @Prop({ type: Boolean })
  percentage: boolean;
}

// Subdocument schema for Supplier Tolerance
@Schema({ _id: false })
class SupplierTolerance {
  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'SupplierConfig' })
  supplierId: Types.ObjectId;

  @Prop({ type: PriceOffsetTolerance })
  priceOffsetTolerance: PriceOffsetTolerance;

  @Prop({ type: Boolean })
  stockAvailabilityFallback: boolean;
}

// Subdocument schema for Quantity Offset
@Schema({ _id: false })
class QuantityOffset {
  @Prop({ type: Number })
  value: number;

  @Prop({ type: Boolean })
  percentage: boolean;
}

// Subdocument schema for Quantity Setup
@Schema({ _id: false })
class QuantitySetup {
  @Prop({ type: MongooseSchema.Types.ObjectId, ref: 'SupplierConfig' })
  supplierId: Types.ObjectId;

  @Prop({ type: QuantityOffset })
  quantityOffset: QuantityOffset;

  @Prop({ type: Boolean })
  defaultMaxQuantityLimitEnabled: boolean;

  @Prop({ type: Number })
  defaultMaxQuantityLimit: number;

  @Prop({ type: [QuantityThresholdAdjustment], default: [] })
  quantityThresholdAdjustments: QuantityThresholdAdjustment[];

  @Prop({ type: [AllowedQuantitiesByPriceRange], default: [] })
  quantitiesByPriceRange: AllowedQuantitiesByPriceRange[];
}

// Subdocument schema for Sourcing Setup
@Schema({ _id: false })
class SourcingSetup {
  @Prop({ type: [SupplierSourcingPriority], default: [] })
  supplierSourcingPriority: SupplierSourcingPriority[];

  @Prop({ type: [SupplierTolerance], default: [] })
  supplierTolerance: SupplierTolerance[];

  @Prop({ type: [QuantitySetup], default: [] })
  quantitySetup: QuantitySetup[];
}

// Subdocument schema for Optimal Pricing Window
@Schema({ _id: false })
class OptimalPricingWindow {
  @Prop({ type: Number, default: null })
  minimumSellerAllowedPricePercent: number;

  @Prop({ type: Number, default: null })
  maximumSellerAllowedPricePercent: number;
}

// Subdocument schema for Marketplace Options
@Schema({ _id: false })
class MarketplaceOptions {
  @Prop({ type: OptimalPricingWindow })
  optimalPricingWindow: OptimalPricingWindow;

  @Prop({ type: String, default: '' })
  sellerId: string;

  @Prop({ type: String, default: '' })
  marketplaceId: string;

  @Prop({ type: String, default: '' })
  issueLocale: string;
}

// Subdocument schema for Analyzer Config
@Schema({ _id: false })
class AnalyzerConfig {
  @Prop({ type: Number, default: null })
  ebayCommissionPercent: number;

  @Prop({ type: Number, default: null })
  minimumProfitPercent: number;
}

// Main Store schema
@Schema({ timestamps: true })
export class Store extends Document {
  @Prop({ enum: ['ebay', 'amazon'], required: true })
  storeMarketplace: string;

  @Prop({ required: true })
  storeName: string;

  @Prop({ required: true })
  storeUsername: string;

  @Prop({ required: true })
  storeEmail: string;

  @Prop({ type: String, required: true })
  storePassword: string;

  @Prop({ type: [String], default: [] })
  supplierIds: string[];

  @Prop({
    type: [{ supplierId: String, markUpPercent: Number }],
    default: [],
  })
  supplierMarkUps: { supplierId: string; markUpPercent: number }[];

  @Prop({ type: Boolean, default: false })
  syncSwitch: boolean;

  @Prop({
    type: {
      switch: Boolean,
      specifiedItemIds: Boolean,
      itemIds: [{ type: MongooseSchema.Types.Mixed }],
    },
    default: { switch: false, specifiedItemIds: false, itemIds: [] },
  })
  fetch: {
    switch: boolean;
    specifiedItemIds: boolean;
    itemIds: any[];
  };

  @Prop({ type: String, default: false })
  storeRedirectUri: string;

  @Prop({ type: Number, default: false })
  storeShipStationId: number;

  @Prop({ type: ApiOAuthToken, default: false })
  apiOAuthToken: ApiOAuthToken;
  
  @Prop({ type: SourcingSetup, default: false })
  sourcingSetup: SourcingSetup;

  @Prop({ type: MarketplaceOptions, default: false })
  marketplaceOptions: MarketplaceOptions

  @Prop({ type: SourcingSetup, default: false })
  analyzerConfig: AnalyzerConfig
  
  @Prop({ type: Boolean, default: false })
  listingDescriptionTemplate: boolean
  
}

export const StoreSchema = SchemaFactory.createForClass(Store);